baseURL = 'https://sebastianmarines.github.io/'
title = 'Sebastian Marines'
theme = 'holy'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
[languages]
  [languages.en]
    disabled = false
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 10
  [languages.es]
    disabled = false
    languageCode = 'es'
    languageDirection = 'ltr'
    languageName = 'Spanish'
    weight = 2
    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "projects"
        name = "Proyectos"
        url = "/projects/"
        weight = 10

[outputs]
home = ["HTML", "RSS"]
